name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "branch_name=${branch_name,,}" >> $GITHUB_ENV
          
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.repository.toLowerCase() }}/bonsaibid:${{ env.branch_name.toLowerCase() }} --tag ghcr.io/${{ github.repository.toLowerCase() }}/bonsaibid:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository.toLowerCase() }}/bonsaibid:${{ env.branch_name.toLowerCase() }}
          docker push ghcr.io/${{ github.repository.toLowerCase() }}/bonsaibid:latest
