name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          echo "branch_name=${branch_name,,}" >> $GITHUB_ENV
          
      - name: Build the Docker image
        run: |
          repo_name=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "Building Docker image for repo: $repo_name and branch: $branch_name"
          docker build . --file Dockerfile --tag ghcr.io/${repo_name}/bonsaibid:${branch_name} --tag ghcr.io/${repo_name}/bonsaibid:latest

      - name: Push Docker image
        run: |
          repo_name=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "Pushing Docker image to ghcr.io/${repo_name}/bonsaibid:${branch_name} and latest"
          docker push ghcr.io/${repo_name}/bonsaibid:${branch_name}
          docker push ghcr.io/${repo_name}/bonsaibid:latest
